In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

Zad 1

In [2]:
print(load_breast_cancer().data)
print(load_breast_cancer().target)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [3]:
dataset = load_breast_cancer()
data = load_breast_cancer().data
target = load_breast_cancer().target
data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
data.shape

(569, 30)

In [5]:
(values, count)=np.unique(target, return_counts = True)
print(values)
print(count)

[0 1]
[212 357]


In [6]:
df_cancer=pd.DataFrame(data, columns=dataset.feature_names)
df_cancer['target'] = pd.Series(target)

Decyzja, które dane dostarczają najmniej inforamcji jest trudna, ponieważ może zaistnieć sytuacja, w której te dane okażą się niezbędne. Zakładając jednak, że chcemy je ograniczyć, wybrałbym kolumny z wartościami średnimi oraz najgorszymi z zebranych materiałów.

In [7]:
df_copy=df_cancer.copy(deep=True)
df_copy = df_copy[df_copy.columns.drop(list(df_copy.filter(regex = 'error')))]
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', None)
df_copy

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  worst radius  worst texture  worst perimeter  \
0                   0.07871        25.380          17.33           184.60   
1                   0.05667        24.990          23.41           158.80   
2                   0.05999        23.570          25.53           152.50   
3                   0.09744        14.910          26.50            98.87   
4                   0.05883        22.540          16.67           152.20   
..                      ...           ...            ...              ...   
564                 0.05623        25.450          26.40           166.10   
565                 0.05533        23.690          38.25           155.00   
566                 0.05648        18.980          34.12           126.70   
567                 0.07016        25.740          39.42           184.60   
568                 0.05884         9.456          30.37            59.16   

     worst area  worst smoothness  worst compactness  worst concavity  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575        

In [8]:
df_copy.to_csv(r'dateset_cut.csv', index=False, sep=';')

W wyniku uruchomienia powyższego kodu otrzymaliśmy zredukowany zbiór danych, ale do dalszych działań wykorzystaliśmy pełen, ponieważ wyniki mogą okazać się dokładniejsze.


Zad 2

In [9]:
data_ready=StandardScaler().fit_transform(data)
pca=PCA(n_components = 5)
components=pca.fit_transform(data_ready)
df = pd.DataFrame(data = components, columns = ['COMP1', 'COMP2', 'COMP3', 'COMP4', 'COMP5'])
df['TARGET'] = df_cancer['target']
df.to_csv(r'dateset_pca_5.csv', index=False, sep=';')
df

COMP1      COMP2     COMP3     COMP4     COMP5  TARGET
0     9.192837   1.948583 -1.123167  3.633731 -1.195113       0
1     2.387802  -3.768172 -0.529292  1.118264  0.621777       0
2     5.733896  -1.075174 -0.551748  0.912083 -0.177088       0
3     7.122953  10.275589 -3.232790  0.152547 -2.960879       0
4     3.935302  -1.948072  1.389767  2.940639  0.546747       0
..         ...        ...       ...       ...       ...     ...
564   6.439315  -3.576817  2.459486  1.177314 -0.074827       0
565   3.793382  -3.584048  2.088477 -2.506028 -0.510722       0
566   1.256179  -1.902297  0.562731 -2.089227  1.809992       0
567  10.374794   1.672010 -1.877029 -2.356031 -0.033742       0
568  -5.475243  -0.670637  1.490442 -2.299156 -0.184708       1

[569 rows x 6 columns]

In [10]:
df.var()

COMP1     13.304991
COMP2      5.701375
COMP3      2.822910
COMP4      1.984128
COMP5      1.651633
TARGET     0.234177
dtype: float64

In [11]:
df.var().sum()

25.699212901694864

In [12]:
pca.explained_variance_ratio_.sum()

0.8473427431680135

Otrzymane wyniki zostaną wykorzystane do porównania z innymi rozwiązaniami

Zad 3

In [13]:
pca = PCA(svd_solver='auto', n_components=0.90)
components = pca.fit_transform(data_ready)
df = pd.DataFrame(data = components, columns = ['COMP1', 'COMP2', 'COMP3', 'COMP4', 'COMP5', 'COMP6', 'COMP7'])
df['TARGET'] = df_cancer['target']
df.to_csv(r'dateset_pca_n.csv', index=False, sep=';')
df

COMP1      COMP2     COMP3     COMP4     COMP5     COMP6     COMP7  \
0     9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159370   
1     2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013358   
2     5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668166   
3     7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053422  1.429911   
4     3.935302  -1.948072  1.389767  2.940639  0.546747 -1.226495 -0.936213   
..         ...        ...       ...       ...       ...       ...       ...   
564   6.439315  -3.576817  2.459487  1.177314 -0.074824 -2.375193 -0.596130   
565   3.793382  -3.584048  2.088476 -2.506028 -0.510723 -0.246710 -0.716326   
566   1.256179  -1.902297  0.562731 -2.089227  1.809991 -0.534447 -0.192758   
567  10.374794   1.672010 -1.877029 -2.356031 -0.033742  0.567936  0.223082   
568  -5.475243  -0.670637  1.490443 -2.299157 -0.184703  1.617837  1.698952   

     TARGET  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
564       0  
565       0  
566       0  
567       0  
568       1  

[569 rows x 8 columns]

In [14]:
df.var()

COMP1     13.304991
COMP2      5.701375
COMP3      2.822910
COMP4      1.984128
COMP5      1.651633
COMP6      1.209482
COMP7      0.676409
TARGET     0.234177
dtype: float64

In [15]:
df.var().sum()

27.58510402320056

In [16]:
pca.explained_variance_ratio_.sum()

0.9100953006967308

Do dobrania odpowiednich ilości komponentów użyliśmy svd_solver z parametrem auto. Wyszło, że dla minimum 90% wariacji potrzeba 7 parametrów. Poskutkowało to wzrostem wariancji wyjaśnionej dla wygenerowanych składowych i wariancji zbioru danych po redukcji.

Zad 4

In [17]:
from sklearn.decomposition import TruncatedSVD

In [18]:
svd = TruncatedSVD(n_components=5, n_iter=5, random_state=42)
a=svd.fit_transform(data_ready)
df = pd.DataFrame(data = a, columns = ['COMP1', 'COMP2', 'COMP3', 'COMP4', 'COMP5'])
df['TARGET'] = df_cancer['target']
df.to_csv(r'dateset_algorithm.csv', index=False, sep=';')
df

COMP1      COMP2     COMP3     COMP4     COMP5  TARGET
0     9.192837   1.948583 -1.123166  3.633731 -1.195110       0
1     2.387802  -3.768172 -0.529293  1.118264  0.621775       0
2     5.733896  -1.075174 -0.551748  0.912083 -0.177086       0
3     7.122953  10.275589 -3.232790  0.152547 -2.960878       0
4     3.935302  -1.948072  1.389767  2.940639  0.546747       0
..         ...        ...       ...       ...       ...     ...
564   6.439315  -3.576817  2.459487  1.177314 -0.074824       0
565   3.793382  -3.584048  2.088476 -2.506028 -0.510723       0
566   1.256179  -1.902297  0.562731 -2.089227  1.809991       0
567  10.374794   1.672010 -1.877029 -2.356031 -0.033742       0
568  -5.475243  -0.670637  1.490443 -2.299157 -0.184703       1

[569 rows x 6 columns]

In [19]:
df.var()

COMP1     13.304991
COMP2      5.701375
COMP3      2.822910
COMP4      1.984128
COMP5      1.651633
TARGET     0.234177
dtype: float64

In [20]:
df.var().sum()

25.69921290169663

In [21]:
svd.explained_variance_ratio_.sum()

0.847342743168071

Wybraliśmy algorytm TruncatedSVD (innaczej LSA) z powodu chęci przetestowania i porównania z PCA. Przy wybranych parametrach dla 5 składowych otrzymaliśmy wyniki bardzo zbiżone do PCA dla takiej samej ilości. Może to być spowodowane tym, że oba algorytmy wykorzystują SVD

Autorzy: Jakub Bembnista, Walter Modrak